---
- name: Installs python3
  hosts: "{{ target }}"
  become: true
  gather_facts: no
  pre_tasks:
    - name: Install python3 
      raw: sudo apt-get install -y python3
  tasks: []

- name: Setup repo and files
  hosts: "{{ target }}"
  tasks: 
    - name: Install required packages
      become: True
      apt: 
        pkg: 
          - ruby-full
          - build-essential
          - zlib1g-dev
          - nodejs
          - npm
          - git
          - build-essential
          - nginx
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Add the user
      user:
        name: '{{ user }}'

    - name: Create www folder
      become: True
      file: path={{ www_location }} state=directory mode=0775 owner={{ user }} group={{ user }}

    - name: Clone bare github repo to user folder
      command: git clone --bare {{ github_repo }} {{ git_bare_repo }}
      args:
        creates: "{{ git_bare_repo }}"
    
    - name: Setup post receive hook
      template: dest={{ git_bare_repo }}/hooks/post-receive src=templates/post-receive mode=0775
    
    - name: Install nodejs version manager
      become: True
      npm: name=n global=yes
    
    - name: Set npm config strict-ssl
      command: npm config -g set strict-ssl false

    - name: Install node
      become: True
      command: n latest

    - name: Add npm install location to PATH and ruby
      become: True
      copy:
        dest: /etc/profile.d/custom-path.sh
        content: 'PATH=$HOME/gems/bin:$PATH:/usr/local/lib'
    
    - name: Register cronjob exporting vars
      cron:
        name="Export VARS"
        special_time=reboot
        job="export GEM_HOME=$HOME/gems"

    - name: Register cronjob start jekyll
      cron:
        special_time=reboot
        job="cd /var/www/devblog && jekyll build && jekyll serve --detach"

    - name: Export VARS for ruby
      shell: export GEM_HOME=$HOME/gems

    - name: Install jekyll
      become: True
      shell: gem install jekyll bundler

    - name: Checkout jekyll
      command: chdir="{{ www_location }}" git --work-tree="{{ www_location }}" --git-dir="{{ git_bare_repo }}" checkout "{{ git_version }}" -f

    - name: Build jekyll
      command: chdir="{{ www_location }}" jekyll build

    - name: Start jekyll
      command: chdir="{{ www_location }}" jekyll serve --detach --watch

    - name: delete default nginx
      file: path=/etc/nginx/sites-enabled/default state=absent

    - name: Copy nginx config
      become: True
      template: dest=/etc/nginx/sites-available/devblog src=templates/nginx.conf

    - name: create symlink
      file:
        src: /etc/nginx/sites-available/devblog
        dest: /etc/nginx/sites-enabled/devblog
        state: link
      become: yes
      notify: restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted enabled=yes
      # ignore if nginx not yet installed
      ignore_errors: True
      become: True
